### ISSUE TITLE
sleep() must have public visibility 

### ISSUE THREAD

**Issue by aab3r** [yeswework/fabrica-evergreen-web#3]
Hi there,

I've been using this plugin for some months, and it works fine (thanks!).

Lately (I wonder if it is related to upgrading from PHP7.4 to PHP8.2) I'm getting this messages in the logs:

`PHP message: PHP Warning:  The magic method Fabrica\EvergreenWeb\Singleton::__sleep() must have public visibility in /wp-content/plugins/fabrica-evergreen-web/inc/singleton.php on line 25; PHP message: PHP Warning:  The magic method Fabrica\EvergreenWeb\Singleton::__wakeup() must have public visibility in /wp-content/plugins/fabrica-evergreen-web/inc/singleton.php on line 28`

They seem to be triggered when someone visits a working post (I mean, a post that should not be redirected). But just sometimes, like 3 or 4 times a day. I can't identify the exact reason of the trigger.

Besides that, the plugin keeps working correctly.

Please, let me know if you need me to make tests.

**Comment by tiojoca** [comment]
Thanks for reporting this issue. We've just pushed some changes to fix PHP8 compatibility, it should work correctly now
